import sys
import os
import re
import requests
import json
import subprocess
from datetime import datetime

OLLAMA_URL = "http://localhost:11434/api/generate"

def get_installed_model():
    try:
        res = requests.get("http://localhost:11434/api/tags", timeout=3)
        if res.status_code == 200:
            models = json.loads(res.text).get("models", [])
            if models:
                for m in models:
                    if "deepseek" in m["name"].lower(): return m["name"]
                for m in models:
                    if "qwen" in m["name"].lower(): return m["name"]
                return models["name"]
    except Exception:
        pass
    return "deepseek-r1:8b"

def run_command(cmd, description):
    print(f"[*] Starting {description}...")
    try:
        result = subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True, timeout=300)
        if result.returncode == 0 or result.stdout:
            print(f"[+] {description} completed successfully.")
            return result.stdout
    except subprocess.TimeoutExpired:
        print(f"[-] {description} timed out after 300 seconds. Moving on with partial data.")
    except Exception as e:
        print(f"[-] Failed to execute {description}: {str(e)}")
    return ""

def ask_local_ai(scan_data, model_name):
    prompt = (
        f"You are an elite Red Team Lead evaluating rich CTF scanner data. Look at the big picture and prioritize. "
        f"Do not output your internal reasoning or <thought> tags. Output ONLY the core results. "
        f"Provide a focused execution plan structured exactly like this:\n\n"
        f"1. THE GOLDEN PATH (The Absolute Best Entry Point):\n"
        f"Give the exact raw exploit command or tool needed to target this specific vulnerability immediately.\n\n"
        f"2. SECONDARY ATTACK VECTOR:\n"
        f"What is the next logical step to gain a foothold?\n\n"
        f"3. RECON QUICK WINS:\n"
        f"Max 2 specific commands based on the web artifacts. Skip all ethical disclaimers, do not guess raw CVE numbers, "
        f"be extremely brief, and output only the command line blocks.\n\n"
        f"TARGET DATA (NMAP, GOBUSTER & NIKTO OUTPUT):\n{scan_data}"
    )
    
    payload = {
        "model": model_name,
        "prompt": prompt,
        "stream": False
    }
    
    try:
        response = requests.post(OLLAMA_URL, json=payload, timeout=300)
        if response.status_code == 200:
            result_text = json.loads(response.text).get('response', '')
            result_text = re.sub(r'<thought>.*?</thought>', '', result_text, flags=re.DOTALL).strip()
            print("\n" + "="*25 + " NETWEAVE CORE INTELLIGENCE CORRELATION " + "="*25)
            print(result_text)
            print("="*94)
            return result_text
        else:
            print(f"\n[-] Analysis core responded with status code: {response.status_code}")
            return ""
    except Exception as e:
        print(f"\n[-] Could not contact local analysis database: {str(e)}")
        return ""

def generate_attack_script(ai_text, ip):
    commands = re.findall(r'(?:^|\s|```)((?:curl|ssh|nmap|nikto|dirb|hydra|nuclei|gobuster|wfuzz|msfconsole|searchsploit)\s[^\n`*]*)', ai_text, re.IGNORECASE)
    if not commands:
        return False
        
    script_filename = f"fire_payloads_{ip.replace('.', '_')}.ps1"
    valid_cmds_found = 0
    try:
        with open(script_filename, "w", encoding="utf-8") as f:
            f.write("# ========================================================\n")
            f.write(f"# AUTOMATED CTF ATTACK SCRIPT GENERATED BY NETWEAVE\n")
            f.write(f"# TARGET: {ip}\n")
            f.write("# ========================================================\n\n")
            
            for cmd in commands:
                clean_cmd = cmd.replace("`", "").replace("'", '"').strip()
                if clean_cmd.startswith('"') and clean_cmd.endswith('"'):
                    clean_cmd = clean_cmd[1:-1].strip()
                
                if " (" in clean_cmd: clean_cmd = clean_cmd.split(" (").strip()
                if " | grep " in clean_cmd: clean_cmd = clean_cmd.replace(" | grep ", " | Select-String ")
                
                lower_cmd = clean_cmd.lower()
                supported_tools = ["curl ", "ssh ", "nmap ", "nikto ", "dirb ", "hydra ", "nuclei ", "gobuster ", "wfuzz ", "msfconsole ", "searchsploit "]
                if not any(lower_cmd.startswith(tool) for tool in supported_tools):
                    continue
                
                if lower_cmd.startswith("curl "):
                    clean_cmd = clean_cmd.replace("curl ", "curl.exe ")
                    
                valid_cmds_found += 1
                f.write(f"Write-Host '[*] Executing Tactical Command #{valid_cmds_found}...' -ForegroundColor Cyan\n")
                f.write(f"Write-Host '>> {clean_cmd}' -ForegroundColor Gray\n")
                f.write(f"{clean_cmd}\n")
                f.write("Write-Host ''\n")
                f.write("Start-Sleep -Seconds 2\n\n")
                
            f.write("Write-Host '[+] All tactical commands deployed.' -ForegroundColor Green\n")
        return script_filename if valid_cmds_found > 0 else False
    except Exception:
        return False

def main():
    print("""
    ███╗   ██╗███████╗████████╗██╗    ██╗███████╗ █████╗ ██╗   ██╗███████╗
    ████╗  ██║██╔════╝╚══██╔══╝██║    ██║██╔════╝██╔══██╗██║   ██║██╔════╝
    ██╔██╗ ██║█████╗     ██║   ██║ █╗ ██║█████╗  ███████║██║   ██║█████╗  
    ██║╚██╗██║██╔══╝     ██║   ██║███╗██║██╔══╝  ██╔══██║╚██╗ ██╔╝██╔══╝  
    ██║ ╚████║███████╗   ██║   ╚███╔███╔╝███████╗██║  ██║ ╚████╔╝ ███████╗
    ╚═╝  ╚═══╝╚══════╝   ╚═╝    ╚══╝╚══╝ ╚══════╝╚═╝  ╚═╝  ╚═══╝  ╚══════╝
    """)
    print(" >>> NetWeave v7.0 - Recon & Attack Path Correlation Framework <<<")
    
    active_model = get_installed_model()
    print(f"[*] Engine Status: Core Analysis Module ONLINE ({active_model})")
    
    print("Enter Target IP: ", end="")
    ip = input().strip()
    if not ip: return

    scan_report = f"TARGET: {ip}\nSCAN TIME: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n"
    
    nmap_cmd = ["nmap", "-sV", "-T4", "--version-light", "--script=vuln", "--top-ports", "100", ip]
    nmap_output = run_command(nmap_cmd, "Deep Nmap Vulnerability Scan")
    scan_report += "=== NMAP VULNERABILITY REPORT ===\n" + nmap_output + "\n"
    
    has_web = any(p in nmap_output for p in ["80/tcp", "443/tcp", "8080/tcp"])
    
    if has_web:
        print("[!] Web interface detected. Spawning sub-recon suites...")
        
        wordlist = "/usr/share/wordlists/dirb/common.txt"
        if os.path.exists(wordlist):
            gobuster_cmd = ["gobuster", "dir", "-u", f"http://{ip}", "-w", wordlist, "-q", "-t", "20", "--timeout", "10s"]
            gobuster_output = run_command(gobuster_cmd, "Gobuster Directory Brute-Force")
            scan_report += "=== GOBUSTER DIRECTORY ARTIFACTS ===\n" + gobuster_output + "\n"
        else:
            scan_report += "=== GOBUSTER ===\nStandard Kali wordlist not found. Skipping brute-force.\n"
            
        nikto_cmd = ["nikto", "-h", f"http://{ip}", "-Tuning", "1,2,3,4,8,9", "-maxtime", "60s"]
        nikto_output = run_command(nikto_cmd, "Nikto Web Vulnerability Scanner")
        scan_report += "=== NIKTO WEB ASSESSMENT ===\n" + nikto_output + "\n"

    print("\n[*] COUPLING RECON DATA WITH LOCAL INTELLIGENCE DATABASE...")
    ai_analysis = ask_local_ai(scan_report, active_model)
    
    if ai_analysis:
        script_file = generate_attack_script(ai_analysis, ip)
        if script_file:
            print(f"\n[███] SUCCESS: Automated execution payload created: {os.getcwd()}/{script_file} 🔥")
            print(f"[!] Run this script in PowerShell to execute the automated attack chain!")
        else:
            print("\n[-] AI provided analysis but no actionable attack commands could be parsed.")

if __name__ == "__main__":
    main()
