import socket
import sys
import os
import re
import requests
import json
from datetime import datetime

OLLAMA_URL = "http://localhost:11434/api/generate"

def get_installed_model():
    try:
        res = requests.get("http://localhost:11434/api/tags", timeout=3)
        if res.status_code == 200:
            models = json.loads(res.text).get("models", [])
            if models:
                for m in models:
                    if "deepseek" in m["name"].lower(): return m["name"]
                for m in models:
                    if "qwen" in m["name"].lower(): return m["name"]
                return models[0]["name"]
    except Exception:
        pass
    return "deepseek-r1:8b"

def get_banner(ip, port):
    # För webbportar använder vi requests för att få en pålitlig Server-header
    if port in:
        try:
            proto = "https" if port == 443 else "http"
            url = f"{proto}://{ip}:{port}/"
            res = requests.head(url, timeout=2, headers={"User-Agent": "NetWeave/6.5"}, verify=False)
            server = res.headers.get("Server")
            if server:
                return server.strip()
        except Exception:
            pass

    # Standard banner-grabbing via sockets för övriga portar
    try:
        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
            s.settimeout(1.5)
            s.connect((ip, port))
            # Vissa tjänster kräver att man skickar data först för att svara
            if port in:
                banner = s.recv(1024).decode("utf-8", errors="ignore").strip()
            else:
                s.sendall(b"\r\n")
                banner = s.recv(1024).decode("utf-8", errors="ignore").strip()
            
            if banner:
                return banner[:60].replace('\r\n', ' ').strip()
    except Exception:
        pass
    return "Unknown Service"

def ask_local_ai(scan_data, model_name):
    # Prompten har optimerats för att förhindra att deepseek-r1 dumpar hela sin <thought>-process i skriptet
    prompt = (
        f"You are an elite Red Team Lead evaluating CTF data. Look at the big picture and prioritize. "
        f"Do not output your internal reasoning or <thought> tags. Output ONLY the core results. "
        f"Provide a focused execution plan structured exactly like this:\n\n"
        f"1. THE GOLDEN PATH (The Absolute Best Entry Point):\n"
        f"Give the exact raw exploit command or tool needed to target this specific vulnerability immediately.\n\n"
        f"2. SECONDARY ATTACK VECTOR:\n"
        f"What is the next logical step to gain a foothold?\n\n"
        f"3. RECON QUICK WINS:\n"
        f"Max 2 specific commands based on the web artifacts. Skip all ethical disclaimers, do not guess raw CVE numbers, "
        f"be extremely brief, and output only the command line blocks.\n\n"
        f"TARGET DATA:\n{scan_data}"
    )
    
    payload = {
        "model": model_name,
        "prompt": prompt,
        "stream": False
    }
    
    try:
        response = requests.post(OLLAMA_URL, json=payload, timeout=300)
        if response.status_code == 200:
            result_text = json.loads(response.text).get('response', '')
            # Snygga till utskriften genom att rensa bort eventuella kvarvarande thought-taggar manuellt
            result_text = re.sub(r'<thought>.*?</thought>', '', result_text, flags=re.DOTALL).strip()
            print("\n" + "="*25 + " NETWEAVE CORE INTELLIGENCE CORRELATION " + "="*25)
            print(result_text)
            print("="*94)
            return result_text
        else:
            print(f"\n[-] Analysis core responded with status code: {response.status_code}")
            return ""
    except Exception as e:
        print(f"\n[-] Could not contact local analysis database: {str(e)}")
        return ""

def generate_attack_script(ai_text, ip):
    # Denna regex fångar rader som börjar med kända verktyg samt hanterar markdown-kodblock
    commands = re.findall(r'(?:^|\s|```)((?:curl|ssh|nmap|nikto|dirb|hydra|nuclei|gobuster|wfuzz)\s[^\n`*]*)', ai_text, re.IGNORECASE)
    if not commands:
        return False
        
    script_filename = f"fire_payloads_{ip.replace('.', '_')}.ps1"
    valid_cmds_found = 0
    try:
        with open(script_filename, "w", encoding="utf-8") as f:
            f.write("# ========================================================\n")
            f.write(f"# AUTOMATED CTF ATTACK SCRIPT GENERATED BY NETWEAVE\n")
            f.write(f"# TARGET: {ip}\n")
            f.write("# ========================================================\n\n")
            
            for cmd in commands:
                clean_cmd = cmd.replace("`", "").replace("'", '"').strip()
                if clean_cmd.startswith('"') and clean_cmd.endswith('"'):
                    clean_cmd = clean_cmd[1:-1].strip()
                
                if " (" in clean_cmd: clean_cmd = clean_cmd.split(" (")[0].strip()
                
                if " | grep " in clean_cmd:
                    clean_cmd = clean_cmd.replace(" | grep ", " | Select-String ")
                
                lower_cmd = clean_cmd.lower()
                supported_tools = ["curl ", "ssh ", "nmap ", "nikto ", "dirb ", "hydra ", "nuclei ", "gobuster ", "wfuzz "]
                if not any(lower_cmd.startswith(tool) for tool in supported_tools):
                    continue
                
                if lower_cmd.startswith("curl "):
                    clean_cmd = clean_cmd.replace("curl ", "curl.exe ")
                    
                valid_cmds_found += 1
                f.write(f"Write-Host '[*] Executing Tactical Command #{valid_cmds_found}...' -ForegroundColor Cyan\n")
                f.write(f"Write-Host '>> {clean_cmd}' -ForegroundColor Gray\n")
                f.write(f"{clean_cmd}\n")
                f.write("Write-Host ''\n")
                f.write("Start-Sleep -Seconds 2\n\n")
                
            f.write("Write-Host '[+] All tactical commands deployed.' -ForegroundColor Green\n")
        return script_filename if valid_cmds_found > 0 else False
    except Exception:
        return False

def main():
    print("""
    ███╗   ██╗███████╗████████╗██╗    ██╗███████╗ █████╗ ██╗   ██╗███████╗
    ████╗  ██║██╔════╝╚══██╔══╝██║    ██║██╔════╝██╔══██╗██║   ██║██╔════╝
    ██╔██╗ ██║█████╗     ██║   ██║ █╗ ██║█████╗  ███████║██║   ██║█████╗  
    ██║╚██╗██║██╔══╝     ██║   ██║███╗██║██╔══╝  ██╔══██║╚██╗ ██╔╝██╔══╝  
    ██║ ╚████║███████╗   ██║   ╚███╔███╔╝███████╗██║  ██║ ╚████╔╝ ███████╗
    ╚═╝  ╚═══╝╚══════╝   ╚═╝    ╚══╝╚══╝ ╚══════╝╚═╝  ╚═╝  ╚═══╝  ╚══════╝
    """)
    print(" >>> NetWeave v6.5 - Advanced Threat Intelligence & Recon Framework <<<")
    
    active_model = get_installed_model()
    print(f"[*] Engine Status: Core Analysis Module ONLINE ({active_model})")
    
    print("Enter Target IP: ", end="")
    ip = input().strip()
    if not ip: return

    scan_report = f"TARGET: {ip}\nSCAN TIME: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n[PORT RESULTS]\n"
    
    # Utökad med fler standardportar för CTF (t.ex. SMB 445, FTP 21, MySQL 3306)
    ports_to_scan = [21, 22, 23, 25, 53, 80, 139, 443, 445, 3306, 8080, 8081]
    open_ports = {}
    
    print("\n[*] Mapping target attack surface...")
    for port in ports_to_scan:
        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
            s.settimeout(1.0)
            if s.connect_ex((ip, port)) == 0:
                banner = get_banner(ip, port)
                result_line = f"  ▶ Port {port}/tcp is OPEN | Service/Banner: {banner}"
                print(result_line)
                scan_report += result_line + "\n"
                open_ports[port] = banner

    # Kontrollera om det finns öppna webbportar
    web_ports = [p for p in [80, 443, 8080, 8081] if p in open_ports]

    if web_ports:
        scan_report += "\n[WEB ARTIFACTS]\n"
        for w_port in web_ports:
            proto = "https" if w_port == 443 else "http"
            base_url = f"{proto}://{ip}:{w_port}"
            try:
                res = requests.get(base_url, timeout=4, headers={"User-Agent": "NetWeave/6.5"}, verify=False)
                
                # Extrahera HTML-kommentarer
                comments = re.findall(r"<!--(.*?)-->", res.text, re.DOTALL)
                if comments:
                    print(f"  [!] Port {w_port}: Extracted {len(comments)} hidden HTML fragments.")
                    for c in comments: 
                        if c.strip(): scan_report += f"  ▶ [Port {w_port}] Hidden Comment: {c.strip()}\n"
                
                # Utökad ordlista för vanliga CTF-sökvägar och känsliga filer
                dirs = [
                    "/admin", "/secret", "/robots.txt", "/.git", "/config", 
                    "/.env", "/api", "/backup", "/index.php.bak", "/login"
                ]
                for path in dirs:
                    path_res = requests.get(base_url + path, timeout=1.5, allow_redirects=False, verify=False)
                    status = path_res.status_code
                    if status in:
                        dir_line = f"  ▶ [Port {w_port}] Directory Artifact: {path} (Status: {status})"
                        scan_report += dir_line + "\n"
            except Exception:
                pass

    # Skicka insamlad data till den lokala AI-modellen
    ai_analysis = ask_local_ai(scan_report, active_model)
    
    if ai_analysis:
        # Generera det automatiserade attackskriptet baserat på AI-svaret
        script_file = generate_attack_script(ai_analysis, ip)
        if script_file:
            print(f"\n[+] Tactical workflow successfully generated: {script_file}")
            print(f"[*] Review the script contents before executing.")
        else:
            print("\n[-] AI provided analysis but no executable tactical commands could be extracted.")

if __name__ == "__main__":
    main()

            print("[-] No valid attack vectors found in database output to automate.")

if __name__ == "__main__":
    main()
