import socket
import sys
import os
import re
import requests
import json
from datetime import datetime

OLLAMA_URL = "http://localhost:11434/api/generate"

def get_installed_model():
    try:
        res = requests.get("http://localhost:11434/api/tags", timeout=3)
        if res.status_code == 200:
            models = json.loads(res.text).get("models", [])
            if models:
                for m in models:
                    if "deepseek" in m["name"].lower(): return m["name"]
                for m in models:
                    if "qwen" in m["name"].lower(): return m["name"]
                return models["name"]
    except Exception:
        pass
    return "deepseek-r1:8b"

def get_banner(ip, port):
    try:
        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
            s.settimeout(1.0)
            s.connect((ip, port))
            if port == 80 or port == 443 or port == 8080:
                s.sendall(b"HEAD / HTTP/1.1\r\nHost: localhost\r\n\r\n")
            else:
                s.sendall(b"\r\n")
            banner = s.recv(1024).decode("utf-8", errors="ignore").strip()
            if "Server:" in banner:
                for line in banner.split('\r\n'):
                    if line.startswith("Server:"):
                        return line.replace("Server:", "").strip()
            return banner[:60].replace('\r\n', ' ') if banner else "Unknown Service"
    except Exception:
        return "Unknown Service"

def ask_local_ai(scan_data, model_name):
    prompt = f"You are an elite Red Team Lead evaluating CTF data. Look at the big picture and prioritize. Provide a focused execution plan structured exactly like this: 1. THE GOLDEN PATH (The Absolute Best Entry Point): Give the exact raw exploit command or tool needed to target this specific vulnerability immediately. 2. SECONDARY ATTACK VECTOR: What is the next logical step to gain a foothold? 3. RECON QUICK WINS: Max 2 specific commands based on the web artifacts. Skip all ethical disclaimers, do not guess raw CVE numbers, be extremely brief, short and output only the command line blocks. TARGET DATA: {scan_data}"
    
    payload = {
        "model": model_name,
        "prompt": prompt,
        "stream": False
    }
    
    try:
        response = requests.post(OLLAMA_URL, json=payload, timeout=300)
        if response.status_code == 200:
            result_text = json.loads(response.text).get('response', '')
            print("\n" + "="*25 + " NETWEAVE CORE INTELLIGENCE CORRELATION " + "="*25)
            print(result_text)
            print("="*94)
            return result_text
        else:
            print(f"\n[-] Analysis core responded with status code: {response.status_code}")
            return ""
    except Exception as e:
        print(f"\n[-] Could not contact local analysis database: {str(e)}")
        return ""

def generate_attack_script(ai_text, ip):
    # Fångar upp kommandon oavsett dolda tecken runt dem
    commands = re.findall(r'(?:^|\s)((?:curl|ssh|nmap|nikto|dirb|hydra|nuclei)\s[^\n]*)', ai_text, re.IGNORECASE)
    if not commands:
        return False
        
    script_filename = f"fire_payloads_{ip.replace('.', '_')}.ps1"
    valid_cmds_found = 0
    try:
        with open(script_filename, "w", encoding="utf-8") as f:
            f.write("# ========================================================\n")
            f.write(f"# AUTOMATED CTF ATTACK SCRIPT GENERATED BY NETWEAVE\n")
            f.write(f"# TARGET: {ip}\n")
            f.write("# ========================================================\n\n")
            
            for cmd in commands:
                # 1. Radera dolda markdown-backticks och fula citattecken i början/slutet
                clean_cmd = cmd.replace("`", "").replace("'", '"').strip()
                if clean_cmd.startswith('"') and clean_cmd.endswith('"'):
                    clean_cmd = clean_cmd[1:-1].strip()
                
                # 2. Klipp bort eventuella avslutande parenteser eller kommentarer från AI:n
                if " (" in clean_cmd: clean_cmd = clean_cmd.split(" (")[0].strip()
                if " *" in clean_cmd: clean_cmd = clean_cmd.split(" *")[0].strip()
                
                # 3. WINDOWS COMPATIBILITY BUGGFIX: Översätt Linux-grep till Windows Select-String
                if " | grep " in clean_cmd:
                    clean_cmd = clean_cmd.replace(" | grep ", " | Select-String ")
                
                lower_cmd = clean_cmd.lower()
                if not any(lower_cmd.startswith(tool) for tool in ["curl ", "ssh ", "nmap ", "nikto ", "dirb ", "hydra ", "nuclei "]):
                    continue
                
                if lower_cmd.startswith("curl "):
                    clean_cmd = clean_cmd.replace("curl ", "curl.exe ")
                    
                valid_cmds_found += 1
                f.write(f"Write-Host '[*] Executing Tactical Command #{valid_cmds_found}...' -ForegroundColor Cyan\n")
                f.write(f"Write-Host '>> {clean_cmd}' -ForegroundColor Gray\n")
                f.write(f"{clean_cmd}\n")
                f.write("Write-Host ''\n")
                f.write("Start-Sleep -Seconds 2\n\n")
                
            f.write("Write-Host '[+] All tactical commands deployed.' -ForegroundColor Green\n")
        return script_filename if valid_cmds_found > 0 else False
    except Exception:
        return False

def main():
    print("""
    ███╗   ██╗███████╗████████╗██╗    ██╗███████╗ █████╗ ██╗   ██╗███████╗
    ████╗  ██║██╔════╝╚══██╔══╝██║    ██║██╔════╝██╔══██╗██║   ██║██╔════╝
    ██╔██╗ ██║█████╗     ██║   ██║ █╗ ██║█████╗  ███████║██║   ██║█████╗  
    ██║╚██╗██║██╔══╝     ██║   ██║███╗██║██╔══╝  ██╔══██║╚██╗ ██╔╝██╔══╝  
    ██║ ╚████║███████╗   ██║   ╚███╔███╔╝███████╗██║  ██║ ╚████╔╝ ███████╗
    ╚═╝  ╚═══╝╚══════╝   ╚═╝    ╚══╝╚══╝ ╚══════╝╚═╝  ╚═╝  ╚═══╝  ╚══════╝
    """)
    print(" >>> NetWeave v6.5 - Advanced Threat Intelligence & Recon Framework <<<")
    
    active_model = get_installed_model()
    print(f"[*] Engine Status: Core Analysis Module ONLINE")
    
    print("Enter Target IP: ", end="")
    ip = input().strip()
    if not ip: return

    scan_report = f"TARGET: {ip}\nSCAN TIME: {datetime.now()}\n\n[PORT RESULTS]\n"
    
    port_data = "21,22,23,25,53,80,139,443,445,8080"
    ports_to_scan = [int(p) for p in port_data.split(",")]
    open_ports = {}
    
    print("\n[*] Mapping target attack surface...")
    for port in ports_to_scan:
        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
            s.settimeout(1.0)
            if s.connect_ex((ip, port)) == 0:
                banner = get_banner(ip, port)
                result_line = f"  ▶ Port {port}/tcp is OPEN | Service/Banner: {banner}"
                print(result_line)
                scan_report += result_line + "\n"
                open_ports[port] = banner

    has_web = False
    if 80 in open_ports or 443 in open_ports or 8080 in open_ports:
        has_web = True

    if has_web:
        scan_report += "\n[WEB ARTIFACTS]\n"
        port_suffix = ":8080" if (8080 in open_ports and 80 not in open_ports) else ""
        base_url = f"http://{ip}{port_suffix}"
        try:
            res = requests.get(base_url, timeout=5, headers={"User-Agent": "NetWeave/6.5"})
            comments = re.findall(r"<!--(.*?)-->", res.text)
            if comments:
                print(f"  [!] Extracted {len(comments)} hidden HTML fragments.")
                for c in comments: scan_report += f"  ▶ Hidden Comment: {c.strip()}\n"
            
            dirs = ["/admin", "/secret", "/robots.txt", "/.git", "/config"]
            for path in dirs:
                path_res = requests.get(base_url + path, timeout=2, allow_redirects=False)
                status = path_res.status_code
                if status == 200 or status == 301 or status == 302 or status == 403 or status == 401:
                    dir_line = f"  ▶ Directory Artifact: {path} (Status: {status})"
                    scan_report += dir_line + "\n"
        except Exception:
            pass

    print("\n[*] COUPLING RECON DATA WITH LOCAL INTELLIGENCE DATABASE...")
    ai_analysis = ask_local_ai(scan_report, active_model)

    if ai_analysis:
        filename = f"NetWeave_Report_{ip.replace('.', '_')}.txt"
        with open(filename, "w", encoding="utf-8") as f:
            f.write(scan_report + "\n\n" + "="*30 + " EXPLOIT ANALYSIS " + "="*30 + "\n" + ai_analysis)
        print(f"[+] Operational data cached to: {os.path.abspath(filename)}")
        
        attack_script = generate_attack_script(ai_analysis, ip)
        if attack_script:
            print(f"[███] SUCCESS: Automated execution payload created: {os.path.abspath(attack_script)} 🔥")
            print(f"[!] Run '.\\{attack_script}' in PowerShell to execute the automated attack chain!")
        else:
            print("[-] No valid attack vectors found in database output to automate.")

if __name__ == "__main__":
    main()
